name: run multiple jobs using needs

on:
  push

jobs:
  build-jobs-1:
    runs-on: ubuntu-latest
    steps:
    - name: install cowsay program
      run: sudo apt install cowsay -y

    - name: execute cowsay cmd
      run: cowsay -f dragon "Run for  cover, I am a DRAGON...RAWR" >> dragon.txt

    - name: sleep for 30 sec
      run: sleep 30


  test-job-2:
    needs: build-jobs-1
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 sec
      run: sleep 10

    - name: Test file exists
      run: grep -i "dragon" dragon.txt


  deploy-job-3:
    needs: test-job-2
    runs-on: ubuntu-latest
    steps:
    - name: read file
      run: cat dragon.txt