name: execute shell script on workflow
on:
    push

jobs:
  execute-shell-script-on-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -lrt

      - name: Execute shell script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh