name: my first workflow

on:
    push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: list and read file
              run: |
                echo "My first github action job"
                ls -ltra
                cat README.md
            
